### PR TITLE
Updating Hashicorp requirements

### PR DESCRIPTION
**Pull request by rawmind0**
This PR contains:

- CHANGELOG.md file
- .travis.yml file
- hashicorp scripts to `make` actions.
- Converted GNUmakefile  to hashicorp ci process.

Solves issue https://github.com/rancher/terraform-provider-rancher2/issues/39

### CODE REVIEW

**Comment by cgriggs01** [comment]
Hey Raul,

All these changes look good. 

- The goal of the `testacc` make target is to run the entire acceptance test suite for the provider. Since this provider requires a docker environment to be deployed, can you add the necessary calls and scripts to spin up Docker, run acceptance tests, shut down Docker env.

**Comment by rawmind0** [comment]
Hey Chris,

thanks for the review.

Some questions, in order to clarify how to deploy requirements (dockerized rancher server and rke dind cluster or k3s) to run the entire acceptance test suite for the provider:
- Is it supposed that docker daemon is already running at your travis agents??
- Could we download binaries from the pipelines (docker, rke, k3s,..)??
- Could we run the entire acceptance test suite from a docker??

**Comment by cgriggs01** [comment]
Hey Raul,

Yes, there is a docker daemon on the TeamCity CI env that all the providers are tested on. There are a few providers that run against docker versions of their own apps. 

The Travis agent is used just run a compile test, so there is no need for running the acceptance tests there.

**Comment by rawmind0** [comment]
Hey Chris,

added scripts to run full suite of Acceptance tests. Running `make testacc`, `scripts/gotestacc.sh` will be run, deploying all needed requirements (rancher server and k3s cluster), running acceptance tests and making cleanup when it's finished.

Please, take a look.

**Comment by cgriggs01** [comment]
Hey Raul, 

Thanks for the update. I'll rebase and start running the tests. 
Chris

**Comment by cgriggs01** [comment]
Raul,

I am working out of this new code, but when I start `Docker` and run `make testacc` there is a timeout error occurring each run. Is there some other configuring that must be done to run these acceptance tests?

I've include the [output.txt](https://github.com/rancher/terraform-provider-rancher2/files/2954583/output.txt) that had a detailed output of the run. 

Thanks for your help!
Chris

**Comment by rawmind0** [comment]
Hey Chris,

what strange, i saw that timeout occurs trying to login to rancher server to get user token. Is timeout occurring every time on same step?? What is the size of the host your are running acceptance tests?? Is the rancher server docker dying?? I made tests on a ubuntu with 4 Gb ram and they were passing fine...[output.txt](https://github.com/rancher/terraform-provider-rancher2/files/2954664/output.txt)

**Comment by cgriggs01** [comment]
The docker host Im running is through Docker Desktop on my local OSx machine. 

Not sure if that has a defined size or is dynamically allocated when image is deployed.

**Comment by cgriggs01** [comment]
Thanks for sending your successful acceptance test run output. Im seeing that you at 35% test coverage, which is a great start, our goal is to have at least 50% test coverage across all Terraform providers, this is not a huge blocker for release, but something to keep in mind. 

Best,
Chris

**Comment by rawmind0** [comment]
Oh, not working on docker osx due to Docker Desktop for osx can’t route traffic to containers, https://docs.docker.com/docker-for-mac/networking/#known-limitations-use-cases-and-workarounds
That's why you got timeout. Working fine on linux host.

**Comment by rawmind0** [comment]
Ok, thanks for the advice. We'll work on extend test coverage to get at least 50%. :)

**Comment by rawmind0** [comment]
Chris, 

i've made some changes on scripts to full suite of Acceptance tests and now they are also working on osx docker desktop, running `TESTACC_EXPOSE_HOST_PORTS=true make testacc`

I've also updated default value of `TEST?="./${PKG_NAME}”` on GNUMakefile to resolve issue with `make test-compile`

**Comment by cgriggs01** [comment]
Thanks for that env variable, tests are successfully running locally and all passing! 

Thanks for your all your help with this

**Comment by cgriggs01** [comment]
LGTM!

**Pull request merged**
